name: MAIN Release
on:
  release:
    types:
      - published
  workflow_dispatch:

env:
  MS_URL: "https://marketplace.visualstudio.com/items?itemName=eliostruyf.vscode-ghostwriter"
  VSX_URL: "https://open-vsx.org/extension/eliostruyf/vscode-ghostwriter"

jobs:
  build-and-test:
    uses: ./.github/workflows/release-common.yml
    with:
      build_command: npm run vscode:build
      lint_command: npm run lint
      prepare_beta_command: ""
      working_directory: ./

  release-ms:
    name: "Release to VSCode Marketplace"
    runs-on: ubuntu-latest
    needs: build-and-test
    environment:
      name: "Microsoft Marketplace"
      url: ${{ env.MS_URL }}

    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: vscode-extension-build
          path: apps/vscode-extension

      - name: Publish
        run: npx @vscode/vsce publish -p ${{ secrets.VSCE_PAT }} --no-dependencies
        working-directory: apps/vscode-extension

  release-vsx:
    name: "Release to Open VSX"
    runs-on: ubuntu-latest
    needs: build-and-test

    environment:
      name: "Open VSX"
      url: ${{ env.VSX_URL }}

    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: vscode-extension-build
          path: apps/vscode-extension

      - name: Publish to open-vsx.org
        run: npx ovsx publish -p ${{ secrets.OPEN_VSX_PAT }} --no-dependencies
        working-directory: apps/vscode-extension
